### ISSUE TITLE
Binarylang deserves place in this list

### ISSUE THREAD

**Issue by arkanoid87** [ringabout/awesome-nim#44]
I've been using @sealmove [Binarylang](https://github.com/sealmove/binarylang)  extensively for my projects, and it really makes Nim shine compared to what would require to do the same in other system languages.

**Comment by ArikRahman** [comment]
What section would you file the tool under?

**Comment by sealmove** [comment]
Parsing

**Comment by ArikRahman** [comment]
Thanks @sealmove  and @arkanoid87 , I just put in the pull request!
